% tesa_interpdata()     - replaces removed data using interpolated data.
%                           Note that either tesa_removedata or
%                           pop_tesa_removedata must be ran prior to this function.
% Usage:
%   >>  EEG = tesa_interpdata( EEG, interpolation );
%   >>  EEG = tesa_interpdata( EEG, interpolation, interpWin );
%
% Inputs:
%   EEG                 - EEGLAB EEG structure
%   interpolatation     - string describing type of interpolation, either
%                           'linear' or 'cubic'
%   interpWin           - (optional) vector with times before and after
%                           artefact window for fitting cubic function. 
%                           default = [20,20];
%    
% Outputs:
%   EEG                 - EEGLAB EEG structure
% 
% Examples
%   EEG = tesa_interpdata( EEG, 'linear' ); %replaces missing data with linear interpolation. Linear function is fitted on data point before and after missing data.
%   EEG = tesa_interpdata( EEG, 'cubic', [50,50] ); %replaces mising data with cubic interpolation. Cubic is fitted on data 50 ms before and 50 ms after missing data
%
% See also:
%   tesa_removedata

% Copyright (C) 2016  Nigel Rogasch, Monash University,
% nigel.rogasch@monash.edu
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

% Change log:
% 15.6.2018: Changed function to work on both continuous and epoched data

function EEG = tesa_interpdata( EEG, interpolation, interpWin )

if nargin < 2
    error('Not enough input arguments.');
end

if nargin < 3
    interpWin = [20,20];
end

if isempty(interpWin)
    interpWin = [20,20];
end

%Check input for interpolation
if ~(strcmp(interpolation,'linear') || strcmp(interpolation,'cubic') || strcmp(interpolation,'arblend'))
    error('Interpolation input must be either linear or cubic');
end

%Check EEG structure for tmscut fields generated by tesa_removedata.m
if ~isfield(EEG,'tmscut')
    error('Artifact data not removed. Please run pop_tesa_removedata first.');
end

% %Check that tmscut fields generated by tesa_removedata.m contain data
% if isfield(EEG,'tmscut')
%     if isempty(EEG.tmscut(1).tmscut1) || isempty(EEG.tmscut(1).tmscut2)
%         error('Artifact removal time points do not contain data. Please re-run pop_tesa_removedata.');
%     end
% end

% %Check that tmscut fields include interpEvent
% for z = 1:size(EEG.tmscut,2)
%     if strcmp(EEG.tmscut(z).interpolated,'no')
%         eventTemp{x,1} = EEG.tmscut(z).cutEvent;
%     end
% end
%
% if sum(strcmp(interpEvent,eventTemp)) < 1
%     error('Artifact data not removed for event type ''%s''. Please run pop_tesa_removedata first.',interpEvent);
% end

%Check if data is continuous or epoched and replace data
if size(EEG.data,3) == 1 % Continuous data
    EEGtemp = EEG.data;
    EEGtimes = EEG.times;
    dataType = 'continuous';
elseif size(EEG.data,3) > 1 % Epoched data
    EEGtemp = reshape(EEG.data,size(EEG.data,1),[],1);
    EEGtimes = repmat(EEG.times,1,size(EEG.data,3));
    dataType = 'epoched';
end

% Event names
evNames = {EEG.event.type};

%Interpolate the missing data
if strcmp(interpolation,'linear') %linear interpolation
    
    for z = 1:size(EEG.tmscut,2)
        if strcmp(EEG.tmscut(z).interpolated,'no')
            
            % Extract name of events to cut around
            cutEvent = EEG.tmscut(z).cutEvent;
            
            % Find events
            for evx = 1:length(cutEvent)
                evLogTemp(:,evx) = double(strcmp(cutEvent{evx},evNames));
            end
            
            % Convet to logical
            evLog = sum(evLogTemp,2) > 0;
            
            % Extract latencies
            evLat = [EEG.event.latency];
            evLatOut = round(evLat(evLog));
            
            %fit linear function to data
            for b = 1:length(evLatOut)
                
                % Samples of missing data
                cutWin1 = evLatOut(1,b) + round(EEG.tmscut(z).cutTimesTMS(1,1)*(EEG.srate/1000));
                cutWin2 = evLatOut(1,b) + round(EEG.tmscut(z).cutTimesTMS(1,2)*(EEG.srate/1000));
                
                % Samples for interpolation
                tp1 = cutWin1-1;
                tp2 = cutWin2+1;

%               % Locked time ratio to 0 to prevent badly conditioned
%               warnings at high x values
                x(1,1) = 0; 
                x(1,2) = EEGtimes(tp2)-EEGtimes(tp1);
                
                interpData = [];
                for a = 1:size(EEG.data,1)
                    
                    %Extract data points before and after removed data
                    y(1,1) = EEGtemp(a,tp1);
                    y(1,2) = EEGtemp(a,tp2);
                    
                    %Fit linear function to data points
                    p = polyfit(x,y,1);
                    
                    %Interpolate missing data points
                    X = EEGtimes(1,cutWin1:cutWin2); %missing time points
                    X1 = (X - X(1,1))+(1000/EEG.srate); %align with zero
                    interpData(a,:) = polyval(p,X1);
                    
                    
                end
                
                %Insert interpolated data
                EEGtemp(:,cutWin1:cutWin2) = interpData;
                
            end
            
            %Re-format data
            if strcmp('continuous',dataType)
                EEG.data = EEGtemp;
            elseif strcmp('epoched',dataType)
                EEG.data = reshape(EEGtemp,size(EEG.data,1),size(EEG.data,2),[]);
            end
            
            %display message
            fprintf('Linear interpolation between %d ms and %d ms \n',EEG.tmscut(z).cutTimesTMS(1,1),EEG.tmscut(z).cutTimesTMS(1,2));
            
            %Indicate that interpolation has happened
            EEG.tmscut(z).interpolated = 'yes';
        end
    end
end

if strcmp(interpolation,'cubic') %cubic interpolation
    
    for z = 1:size(EEG.tmscut,2)
        if strcmp(EEG.tmscut(z).interpolated,'no')
            
            % Extract name of events to cut around
            cutEvent = EEG.tmscut(z).cutEvent;
            
            % Find events
            for evx = 1:length(cutEvent)
                evLogTemp(:,evx) = double(strcmp(cutEvent{evx},evNames));
            end
            
            % Convet to logical
            evLog = sum(evLogTemp,2) > 0;
            
            % Extract latencies
            evLat = [EEG.event.latency];
            evLatOut = round(evLat(evLog));
            
            %             %Checks whether data sampling rate has changed
            %             tp1 = []; tp2 = [];
            %             if isequal(EEG.srate,EEG.tmscut(z).srate)
            %                 tp1 = EEG.tmscut(z).tmscut1;
            %                 tp2 = EEG.tmscut(z).tmscut2;
            %             elseif ~isequal(EEG.srate,EEG.tmscut(z).srate)
            %                 [~,tp1] = min(abs(EEG.times-EEG.tmscut(z).cutTimesTMS(1,1)));
            %                 [~,tp2] = min(abs(EEG.times-EEG.tmscut(z).cutTimesTMS(1,2)));
            %             end
            
            %fit cubic function to data
            for b = 1:length(evLatOut)
                
                % Samples to cut before and after event
                cutN1 = round(EEG.tmscut(z).cutTimesTMS(1,1)*(EEG.srate/1000));
                cutN2 = round(EEG.tmscut(z).cutTimesTMS(1,2)*(EEG.srate/1000));
                
                % Samples of missing data
                cutWin1 = evLatOut(1,b) + cutN1;
                cutWin2 = evLatOut(1,b) + cutN2;
                
                %Convert interpWin to samples
                iW1 = round((interpWin(1,1)/1000)*EEG.srate);
                iW2 = round((interpWin(1,2)/1000)*EEG.srate);
                
                %Extract time points before and after removed data
                in1 = round(cutWin1-iW1); in2 = round(cutWin2+iW2);
                x1 = EEGtimes(1,in1:in2);
                x = x1 - x1(1,1); % shift to starting at zero to avoid badly conditioned polynomial warnings at high values of x
                
                % Remove time points from data
                [~,centreT] = min(abs(x1-EEGtimes(1,evLatOut(1,b))));
                TP1 = centreT + cutN1;
                TP2 = centreT + cutN2;
                X = x(:,TP1:TP2);
                x(:,TP1:TP2) = [];
                
                interpData = [];
                for a = 1:size(EEG.data,1)

                    %Extract data points before and after removed data
                    y = EEGtemp(a,in1:in2);
                    y(:,TP1:TP2) = [];
                    
                    %Fit cubic function to data points
                    p = polyfit(x,y,3);
                    
                    %Interpolate missing data points
%                     X = EEGtimes(1,cutWin1:cutWin2); %missing time points
                    interpData(a,:) = polyval(p,X);
                    test1 = polyval(p,x);
                    
                end
                
                %Insert interpolated data
                EEGtemp(:,cutWin1:cutWin2) = interpData;
                
            end
            
            if strcmp('continuous',dataType)
                EEG.data = EEGtemp;
            elseif strcmp('epoched',dataType)
                EEG.data = reshape(EEGtemp,size(EEG.data,1),size(EEG.data,2),[]);
            end
            
            %display message
            fprintf('Cubic interpolation between %d ms and %d ms \n',EEG.tmscut(z).cutTimesTMS(1,1),EEG.tmscut(z).cutTimesTMS(1,2));
            
        end
        
        %Indicate that interpolation has happened
        EEG.tmscut(z).interpolated = 'yes';
    end
end

if strcmp(interpolation,'arblend') % autoregressive blended interpolation
    
    for z = 1:size(EEG.tmscut,2)
        if strcmp(EEG.tmscut(z).interpolated,'no')
            
            % Extract name of events to cut around
            cutEvent = EEG.tmscut(z).cutEvent;
            
            % Find events
            evLogTemp = [];
            for evx = 1:length(cutEvent)
                evLogTemp(:,evx) = double(strcmp(cutEvent{evx},evNames));
            end
            
            % Convert to logical
            evLog = sum(evLogTemp,2) > 0;
            
            % Extract latencies
            evLat = [EEG.event.latency];
            evLatOut = round(evLat(evLog));
            
            % Convert interpWin from ms to samples
            iW1 = round((interpWin(1,1)/1000)*EEG.srate);
            iW2 = round((interpWin(1,2)/1000)*EEG.srate);
            
            % interpolate each removed segment
            for b = 1:length(evLatOut)
                
                if mod(b,10) == 0 || b == 1 || b == length(evLatOut)
                    fprintf('Processing event %d / %d\n', b, length(evLatOut));
                end
                
                % Samples to cut before and after event
                cutN1 = round(EEG.tmscut(z).cutTimesTMS(1,1)*(EEG.srate/1000));
                cutN2 = round(EEG.tmscut(z).cutTimesTMS(1,2)*(EEG.srate/1000));
                
                % Samples of missing data
                cutWin1 = evLatOut(1,b) + cutN1;
                cutWin2 = evLatOut(1,b) + cutN2;
                gapLen = cutWin2 - cutWin1 + 1;
                
                % define left and right context windows
                fitStart = cutWin1 - iW1;
                fitEnd   = cutWin2 + iW2;
                
                % protect boundaries
                if fitStart < 1 || fitEnd > size(EEGtemp,2)
                    warning('Interpolation window exceeds data limits. Falling back to linear interpolation for this segment.');
                    for a = 1:size(EEG.data,1)
                        EEGtemp(a,cutWin1:cutWin2) = local_linear_fill(EEGtemp(a,:), cutWin1, cutWin2);
                    end
                    continue;
                end
                
                interpData = zeros(size(EEG.data,1), gapLen);
                
                for a = 1:size(EEG.data,1)
                    
                    sig = double(EEGtemp(a,:));
                    
                    % left and right segments around the gap
                    leftSeg  = sig(fitStart:cutWin1-1);
                    rightSeg = sig(cutWin2+1:fitEnd);
                    
                    % fallback if context too short
                    if length(leftSeg) < 3 && length(rightSeg) < 3
                        interpData(a,:) = local_linear_fill(sig, cutWin1, cutWin2);
                        continue;
                    end
                    
                    try
                        hasLeft = length(leftSeg) > 2;
                        hasRight = length(rightSeg) > 2;
                        
                        if hasLeft
                            pL = max(1, ceil(length(leftSeg)/3));
                            extrapSig_pre = local_ar_extrapolate(leftSeg, gapLen, pL);
                            extrapSig_pre = extrapSig_pre(length(leftSeg)+1:end);
                        end
                        
                        if hasRight
                            pR = max(1, ceil(length(rightSeg)/3));
                            extrapSig_post = local_ar_extrapolate(fliplr(rightSeg), gapLen, pR);
                            extrapSig_post = fliplr(extrapSig_post(length(rightSeg)+1:end));
                        end
                        
                        if hasLeft && hasRight
                            % sigmoid-like blend, similar to your example
                            xw = linspace(1,0,gapLen);
                            k = 2;
                            
                            % avoid exact 0/1 to prevent Inf/NaN in weight formula
                            epsw = 1e-6;
                            xw(xw <= 0) = epsw;
                            xw(xw >= 1) = 1-epsw;
                            
                            pre_weights = 1 - 1./(1+(1./xw - 1).^-k);
                            post_weights = 1 - pre_weights;
                            
                            interpData(a,:) = extrapSig_pre .* pre_weights + extrapSig_post .* post_weights;
                            
                        elseif hasLeft
                            interpData(a,:) = extrapSig_pre;
                            
                        elseif hasRight
                            interpData(a,:) = extrapSig_post;
                            
                        else
                            interpData(a,:) = local_linear_fill(sig, cutWin1, cutWin2);
                        end
                        
                    catch
                        interpData(a,:) = local_linear_fill(sig, cutWin1, cutWin2);
                    end
                    
                end
                
                % Insert interpolated data
                EEGtemp(:,cutWin1:cutWin2) = interpData;
                
            end
            
            if strcmp('continuous',dataType)
                EEG.data = EEGtemp;
            elseif strcmp('epoched',dataType)
                EEG.data = reshape(EEGtemp,size(EEG.data,1),size(EEG.data,2),[]);
            end
            
            fprintf('AR-blended interpolation between %d ms and %d ms using [%d %d] ms windows\n', ...
                EEG.tmscut(z).cutTimesTMS(1,1), EEG.tmscut(z).cutTimesTMS(1,2), interpWin(1), interpWin(2));
            
        end
        
        EEG.tmscut(z).interpolated = 'yes';
    end
end


end

function fillVals = local_linear_fill(sig, cutWin1, cutWin2)

gapLen = cutWin2 - cutWin1 + 1;

if cutWin1 <= 1 && cutWin2 >= length(sig)
    fillVals = zeros(1,gapLen);
elseif cutWin1 <= 1
    fillVals = repmat(sig(cutWin2+1),1,gapLen);
elseif cutWin2 >= length(sig)
    fillVals = repmat(sig(cutWin1-1),1,gapLen);
else
    tmp = linspace(sig(cutWin1-1), sig(cutWin2+1), gapLen+2);
    fillVals = tmp(2:end-1);
end




end
function y = force_boundary_match(y, leftVal, rightVal)

n = length(y);

if n == 1
    y(1) = (leftVal + rightVal)/2;
    return;
end

d1 = leftVal - y(1);
d2 = rightVal - y(end);

corr = linspace(d1, d2, n);
y = y + corr;

end

function y = force_slope_match(y, leftVal, rightVal, leftSlope, rightSlope)

n = length(y);

if n < 2
    y = force_boundary_match(y, leftVal, rightVal);
    return;
end

t = linspace(0,1,n);

% Current endpoint values/slopes of y
y0 = y(1);
y1 = y(end);
dy0 = y(2) - y(1);
dy1 = y(end) - y(end-1);

% Needed correction at boundaries
A = leftVal - y0;
B = rightVal - y1;
C = leftSlope - dy0;
D = rightSlope - dy1;

% Cubic correction q(t)=a*t^3+b*t^2+c*t+d
% with:
% q(0)=A, q(1)=B, q'(0)=C*(n-1), q'(1)=D*(n-1)
% factor (n-1) because slope in samples differs from derivative in t
Cscaled = C*(n-1);
Dscaled = D*(n-1);

d = A;
c = Cscaled;
rhs1 = B - c - d;
rhs2 = Dscaled - c;

a = rhs2 - 2*rhs1;
b = 3*rhs1 - rhs2;

q = a*t.^3 + b*t.^2 + c*t + d;
y = y + q;

end

function extrapSig = local_ar_extrapolate(sig, numAddedPts, modelOrder)

    if isvector(sig) && size(sig,1) == 1
        sig = sig(:); % make column
    end
    
    if nargin < 3 || isempty(modelOrder)
        modelOrder = max(1, floor(size(sig,1)-1));
    end
    
    modelOrder = min(modelOrder, size(sig,1)-1);
    
    if modelOrder < 1
        extrapSig = [sig; repmat(sig(end), numAddedPts, 1)];
        extrapSig = extrapSig.';
        return;
    end
    
    modelCoeff = arburg(sig, modelOrder);
    
    extrapSig = zeros(size(sig,1) + numAddedPts, 1);
    extrapSig(1:size(sig,1)) = sig;
    
    if any(isnan(modelCoeff))
        if all(sig == 0)
            extrapSig(size(sig,1)+1:end) = 0;
        elseif all(abs(sig - sig(1)) < eps)
            extrapSig(size(sig,1)+1:end) = sig(1);
        else
            extrapSig(size(sig,1)+1:end) = sig(end);
        end
        extrapSig = extrapSig.';
        return;
    end
    
    [~, zf] = filter(-[0 modelCoeff(2:end)], 1, sig, [], 1);
    extrapSig(size(sig,1)+1:end) = filter([0 0], -modelCoeff, zeros(numAddedPts,1), zf, 1);
    
    extrapSig = extrapSig.';
end